### ISSUE TITLE
`dunner validate` command

### ISSUE THREAD

**Issue by agentmilindu** [leopardslab/dunner#55] opened 2019-03-20 07:13 UTC
`dunner validate` will validate the `.dunner.yaml` and if there is an issue, it will show warning m messages.

**Comment by ayushjn20** [comment] 2019-03-22 03:26
Duplicate of #31

**Comment by agentmilindu** [comment] 2019-03-22 10:07
@ayushjn20 I broke down #31 into two tasks

**Comment by apoorvam** [comment] 2019-06-14 07:49
Implemented as part of release v2.1.1. Closing this now.

**Closed by apoorvam** 2019-06-14 07:49 UTC
Labels: gsoc-2019
